version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:6.0
    container_name: pixelseek-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - pixelseek-network

  # Weaviate vector database
  weaviate:
    image: semitechnologies/weaviate:1.17.0
    container_name: pixelseek-weaviate
    restart: always
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'custom-chinese-clip'
      CLUSTER_HOSTNAME: 'node1'
      AUTOSCHEMA_ENABLED: 'false'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - pixelseek-network
    depends_on:
      - chinese-clip-module

  # Chinese-CLIP vectorizer module
  chinese-clip-module:
    image: semitechnologies/custom-module:chinese-clip
    build:
      context: ./chinese-clip
      dockerfile: Dockerfile
    container_name: pixelseek-chinese-clip
    environment:
      ENABLE_CUDA: '0'
    networks:
      - pixelseek-network

  # Redis for Celery
  redis:
    image: redis:7.0
    container_name: pixelseek-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pixelseek-network

  # Django backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pixelseek-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - media_data:/app/media
    depends_on:
      - mongodb
      - weaviate
      - redis
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-development-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/pixelseek
      - WEAVIATE_URL=http://weaviate:8080
      - MEDIA_ROOT=/app/media
      - REDIS_URL=redis://redis:6379/0
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - pixelseek-network

  # Celery worker for background tasks
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pixelseek-celery
    restart: always
    volumes:
      - ./backend:/app
      - media_data:/app/media
    depends_on:
      - backend
      - redis
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-development-key-change-in-production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/pixelseek
      - WEAVIATE_URL=http://weaviate:8080
      - MEDIA_ROOT=/app/media
      - REDIS_URL=redis://redis:6379/0
    command: celery -A pixelseek worker --loglevel=info
    networks:
      - pixelseek-network

volumes:
  mongodb_data:
  weaviate_data:
  redis_data:
  media_data:

networks:
  pixelseek-network:
    driver: bridge